routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\ItemController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::redirect('/', '/dashboard');
Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
Route::resource('categories',App\Http\Controllers\CategoryController::class);
Route::resource('items',App\Http\Controllers\ItemController::class);
Route::resource('transactions',App\Http\Controllers\TransactionController::class);
Route::resource('buildings', App\Http\Controllers\BuildingController::class);
Route::resource('rooms', App\Http\Controllers\RoomController::class);
Route::resource('setting',App\Http\Controllers\SettingController::class);
Route::resource('employees',App\Http\Controllers\EmployeeController::class);
Route::resource('status',App\Http\Controllers\StatusController::class);
Route::resource('sponsor',App\Http\Controllers\SponsorController::class);
Route::get('generate-pdf-item', [App\Http\Controllers\ItemController::class,'createPDF'])->name('download');
Route::get('generate-pdf-transaction', [App\Http\Controllers\TransactionController::class,'createPDF'])->name('download-pdf');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $table = "items";

    protected $fillable = ['category_id','title','price','status','description','sponsored','item_id'];

    public function categories(){
        return $this->belongsTo(Category::class);
    }

    public function transactions(){
        return $this->hasOne(Transaction::class);
    }
    public function statuses(){
        return $this->hasMany(Status::class);
    }
    public function sponsors(){
        return $this->hasMany(Sponsor::class);
    }
    public function image(){
        return $this->hasMany(ImageItem::class);
    }
    // protected static function boot()
    // {
    //     parent::boot();

    //     // auto-sets values on creation
    //     static::creating(function ($query) {
    //         $query->item_id= NULL;
    //     });

    //     // self::creating(function ($model) {
    //     //     $model->uuid = IdGenerator::generate(['table' => 'categories', 'length' => 10, 'prefix' =>'Cate-']);
    //     // });
    // }

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Category;
use App\Models\Status;
use App\Models\Sponsor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\ItemImage;
use Barryvdh\DomPDF\Facade\PDF;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        //
        // $categories = Category::orderBy('id','desc')->paginate(0);
        // $items = Item::orderBy('id','desc')->paginate(5);
        $items = DB::table('items')
            ->join('categories', 'items.category_id', '=', 'categories.id')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            ->join('sponsors', 'items.sponsored', '=', 'sponsors.id')
            ->join('itemimages','itemimages.item_id','=','items.id')
            ->where(function ($query) use ($request) {
                if ($term = $request->term) {
                    $query->orWhere('items.title', 'like', '%' . $term . '%')
                        ->orWhere('categories.category', 'like', '%' . $term . '%');
                }
            })
            ->select('items.id', 'items.title', 'items.price', 'statuses.status', 'sponsors.name', 'categories.category', 'items.description', 'items.item_id','itemimages.url')
            ->orderBy('id', 'asc')->paginate(10);
        // $image = DB::table('items')
        //     ->join('itemimages', 'items.id', '=', 'itemimages.item_id')
        //     ->select('itemimages.url')
        //     ->where('itemimages.item_id', '=', $item->id)->get();
        $countBad = DB::table('items')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            ->where('statuses.status', 'like', '%Bad%')->count();
        $countGood = DB::table('items')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            ->where('statuses.status', 'like', '%Good%')->count();
        $countMedium = DB::table('items')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            ->where('statuses.status', 'like', '%Medium%')->count();
        $countBroken = DB::table('items')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            ->where('statuses.status', 'like', '%Broken%')->count();
        // dd($countBad);

        return view('Item.index')->with(compact('items'))->with(compact('countBad'))->with(compact('countGood'))->with(compact('countMedium'))->with(compact('countBroken'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
        //
        $categories = Category::orderBy('id', 'desc')->get();
        $status = Status::orderBy('id', 'desc')->get();
        $sponsor = Sponsor::orderBy('id', 'desc')->get();
        return view('Item.create')->with(compact('categories'))->with(compact('status'))->with(compact('sponsor'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // $request ->validate([

        // ]);
        // Item::create($request->post());
        $request->validate(['id'=>'unique:items']);
        
        $item = new Item();
        $item['title'] = $request->title;
        $item['description'] = $request->description;
        $item['price'] = $request->price;
        $item['status'] = $request->status;
        $item['category_id'] = $request->category_id;
        $item['sponsored'] = $request->sponsored;
        $item['item_id'] = $request->item_id;
        $item->save();

        $quantity = Category::find($request->category_id);
        $quantity->quantity += 1;
        $quantity->save();

        $data = new ItemImage();

        if ($request->file('images')) {
            $file = $request->file('images');
            $filename = date('YmdHi') . $file->getClientOriginalName();
            $file->move(public_path('public/Image'), $filename);
            $data['url'] = $filename;
        }
        $data['item_id'] = $item->id;
        $data->save();


        return redirect()->route('items.index')->with('success', 'Item has been created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        //
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        //
        $items = DB::table('items')
            ->join('itemimages', 'items.id', '=', 'itemimages.item_id')
            ->select('items.id', 'items.title', 'items.price', 'items.status')
            ->where('items.id', '=', $item->id)
            ->get();
        $image = DB::table('items')
            ->join('itemimages', 'items.id', '=', 'itemimages.item_id')
            ->select('itemimages.url')
            ->where('itemimages.item_id', '=', $item->id)->get();
        $categories = Category::orderBy('id', 'desc')->get();
        $status = Status::orderBy('id', 'desc')->get();
        $sponsor = Sponsor::orderBy('id', 'desc')->get();
        return view('Item.edit')->with(compact('categories'))->with(compact('status'))->with(compact('sponsor'))->with(compact('item'))->with(compact('items'))->with(compact('image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        //

        $item->fill($request->post())->save();

        $image = ItemImage::where('item_id', '=', $item->id);
        // dd($image);

        return redirect()->route('items.index')->with('success', 'Item Has Been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        //
        // dd($item->id);
        $deleteImage = DB::table('itemimages')->where('item_id', '=', $item->id)->delete();
        $item->delete();
        return redirect()->route('items.index')->with('success', 'Item Has Been removed successfully');
    }

    public function createPDF(){
        // dd('hello');
        $data = DB::table('items')->select('title')->distinct()->get();
        // dd($data[0]->title);
        $countBad = DB::table('items')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            // ->where('items.title','like',$data[0]->title)
            ->where(function($query) use ($data){
                    foreach($data as $data1){
                        $query->where('items.title','like',$data1->title,'or');
                    }
            })
            ->where('statuses.status', 'like', '%Bad%')->get();
            // dd($countBad);

        $countGood = DB::table('items')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            // ->where('items.title','like',$data[0]->title)
            ->where(function($query) use ($data){
                foreach($data as $data1){
                    $query->where('items.title','like',$data1->title,'or');
                }
        })
            ->where('statuses.status', 'like', '%Good%')->get();
            // dd($countGood);

        $countMedium = DB::table('items')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            // ->where('items.title','like',$data[0]->title)
            ->where(function($query) use ($data){
                foreach($data as $data1){
                    $query->where('items.title','like',$data1->title,'or');
                }
        })
            ->where('statuses.status', 'like', '%Medium%')->get();

        $countBroken = DB::table('items')
            ->join('statuses', 'items.status', '=', 'statuses.id')
            // ->where('items.title','like',$data[0]->title)
            ->where(function($query) use ($data){
                foreach($data as $data1){
                    $query->where('items.title','like',$data1->title,'or');
                }
        })
            ->where('statuses.status', 'like', '%Broken%')->get();


        return view('Item.itemPDF')->with(compact('data'))->with(compact('countBad'))->with(compact('countGood'))->with(compact('countBroken'))
        ->with(compact('countMedium'));    
    }
   
}

resources/views/Item/create.blade.php
@extends('layouts.app')
@section('title')
Item
@endsection

@section('content')
<div class="container-lg my-4 rounded bg-light">
    <div class="row">
        <div class=" mt-4 d-flex justify-content-center">
            <h2>Add New Item</h2>
        </div>
    </div>
    @if(session('status'))
    <div class="alert alert-success mb-1">
        {{ session('status') }}
    </div>
    @endif
    <div class="p-4">
        <form action="{{ route('items.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row mb-5">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="form-group mb-3">
                        <strong>Item ID:</strong>
                        <input type="text" name="item_id" class="form-control" placeholder="ID">
                    </div>
                    <div class="form-group mb-3">
                        <strong>Item Name:</strong>
                        <input type="text" name="title" class="form-control" placeholder="Item">
                    </div>
                    <div class="d-flex row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 d-flex flex-column mb-3">
                            <strong>Price:</strong>
                            <input type="text" name="price" class="form-control" placeholder="Price">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 d-flex flex-column mb-3">
                            <strong>Status:</strong>
                            <select name="status"  class="p-2 rounded-2">
                                @foreach ($status as $stat )
                                    <option value={{$stat->id}}>{{$stat->status}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                   
                    <div class="d-flex row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 d-flex flex-column mb-3">
                            <strong>Category:</strong>
                            <select name="category_id" class="p-2 rounded-2">
                                @foreach ($categories as $cate )
                                <option value={{$cate->id}}>{{$cate->category}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 d-flex flex-column mb-3">
                            <strong>Sponsor by:</strong>
                            <select name="sponsored" class="p-2 rounded-2">
                                @foreach ($sponsor as $spon )
                                    <option class="" value={{$spon->id}}>{{$spon->name}}</option>
                                @endforeach
                                
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-group mb-3">
                        <strong>Description:</strong>
                        <input type="text" name="description" class="form-control" placeholder="Description">
                    </div>
                </div>

                
                <div class="d-flex justify-content-center col-xs-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="d-flex flex-column">
                        <div class="d-flex justify-content-center mt-3">
                            <input type="file" name="images" id="actual-btn" onchange="loadFile(event)" hidden>
                            <label style="cursor: pointer;" class="btn btn-outline-primary" for="actual-btn">Choose File</label>
                            <span id="file-chosen" class="py-2 ps-2">No file chosen</span>
                        </div>
                        <div class="mt-2 border">
                            <img id="output" width="400" height="300" src="{{ asset('images/default-image.png') }}" />
                        </div>
                        <div class="d-flex justify-content-end mt-3 mb-5">
                            <a class="btn btn-danger" href="{{ route('items.index') }}" enctype="multipart/form-data">
                                Back
                            </a>
                            <button type="submit" class="btn btn-success ms-2">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
       
    </div>
   
   
</div>
<script type="text/javascript">
    var fileChosen = document.getElementById('file-chosen');
    var loadFile = function(event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
        fileChosen.textContent = event.target.files[0].name
    };
</script>

@endsection

resources/views/Item/edit.blade.php
@extends('layouts.app')
@section('title')
Item
@endsection

@section('content')
<div class="container my-4 rounded bg-light ">
    <div class="row">
        <div class="mt-3 d-flex justify-content-center">
            <h2>Edit Item Inventory</h2>
        </div>
    </div>
    @if(session('status'))
    <div class="alert alert-success mb-1 mt-1">
        {{ session('status') }}
    </div>
    @endif
    <div class="mt-3 p-4">
        <form action="{{ route('items.update',$item->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row mb-5">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="form-group mb-3">
                        <strong>Item ID:</strong>
                        <input type="text" name="item_id" class="form-control" placeholder="ID" value="{{$item->item_id}}">
                    </div>
                    <div class="form-group mb-3">
                        <strong>Item Name:</strong>
                        <input type="text" name="title" class="form-control" placeholder="Item" value="{{$item->title}}">
                    </div>

                    <div class="d-flex row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 d-flex flex-column mb-3">

                            <strong>Price:</strong>
                            <input type="text" name="price" class="form-control" placeholder="Price" value="{{$item->price}}">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 d-flex flex-column mb-3">
                            <strong>Status: </strong>
                            <select name="status" class="p-2 rounded-2">
                                @foreach ($status as $stat )
                                        <option value={{$stat->id}} {{$item->status==$stat->id ? 'selected' : ''}} >{{$stat->status}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="d-flex row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 d-flex flex-column mb-3">
                            <strong>Category: </strong>
                            <select name="category_id" class="p-2 rounded-2">
                                @foreach ($categories as $cate )
                                    <option value={{$cate->id}} {{ $item->category_id == $cate->id ? 'selected' : ''}}>{{$cate->category}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 d-flex flex-column mb-3">
                            <strong>Sponsor by:</strong>
                            <select name="sponsored" class="p-2 rounded-2">
                                @foreach ($sponsor as $spon )
                                     <option value={{$spon->id}} {{$item->sponsored == $spon->id ? 'selected' : ''}}>{{$spon->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group mb-3">
                        <strong>Description</strong>
                        <input type="text" name="description" class="form-control" value="{{$item->description}}"></textarea>
                    </div>
                </div>
                <div class="d-flex justify-content-center col-xs-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="d-flex flex-column">
                        <div class="d-flex justify-content-center mt-3">
                            <input type="file" name="images" id="actual-btn" onchange="loadFile(event)" hidden>
                            <label style="cursor: pointer;" class="btn btn-outline-primary" for="actual-btn">Choose File</label>
                            <span id="file-chosen" class="py-2 ps-2">No file chosen</span>
                        </div>
                        <div class="mt-2 border">
                            @foreach ($image as $image1)
                            {{-- {{$image->url}} --}}
                            <img id="output" width="400" height="300" src="{{ url('public/Image/'.$image1->url) }}" alt="">
                            @endforeach
                        </div>
                        <div class="d-flex justify-content-end mt-3 mb-5">
                            <a class="btn btn-danger" href="{{ route('items.index') }}" enctype="multipart/form-data">
                                Back
                            </a>
                            <button type="submit" class="btn btn-success ms-2">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>
{{-- <script type="text/javascript">
        var fileChosen = document.getElementById('file-chosen');
        var loadFile = function(event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
            fileChosen.textContent = event.target.files[0].name
        };
    </script> --}}
@endsection

resources/views/Item/index.blade.php
@extends('layouts.app')
@section('title')
Item
@endsection

@section('content')
<div class="container text-center">
    <h2 class="modal-title p-2" id="buildingModalLabel">Item Inventory</h2>
</div>
<div class="d-flex justify-content-between mb-3">
    {{-- search bar --}}
    <div class="d-flex col-xs-12 col-sm-12 col-md-12 col-lg-12 bg-white p-3 rounded-2">
        <div class="col-sm-3 col-md-4 col-lg-3 me-2 w-90">
            <select class="form-select" aria-label="Default select example" name='term'>
                <option selected>Status</option>
                <option value="1">Good</option>
                <option value="2">Medium</option>
                <option value="3">Bad</option>
                <option value="4">Broken</option>
            </select>
        </div>
        <div class="col-sm-3 col-md-4 col-lg-3 me-2">
            <form action="{{ route('items.index') }}" method="GET" role="search">
                <div class="d-flex">
                    <div class="input-group">
                        <input type="text" class="form-control w-100" name="term" placeholder="Search Item" id="term">
                    </div>
                    <span class="input-group-btn ms-2">
                        <button class="btn btn-primary d-flex align-items-center h-100" type="submit" title="Search Item">
                            <i style=" font-size: 18px;" class='bx bx-search'></i>
                        </button>
                    </span>

                </div>
            </form>
        </div>

        <div class="col-xs-6 col-sm-6 col-md-4 col-lg-6 d-flex justify-content-end pe-3">
            <a class="text-white text-decoration-none me-2" href="{{ route('download')}}">
                <div class="btn btn-info d-flex justify-conten-between text-white">
                    <div class="me-2 d-flex align-items-center">
                        <i style="font-size: 18px;" class='bx bx-export'></i>
                    </div>
                    <span>Export</span>
                </div>
            </a>
            <a class="btn btn-primary d-flex justify-conten-between" href="{{ route('items.create') }}">
                <div class="me-2 d-flex align-items-center">
                    <i style="font-size: 18px;" class='bx bx-plus text-white'></i>
                </div>
                <span>Add New</span>
            </a>
        </div>
    </div>

</div>
<div class="my-2 w-100 d-flex justify-content-between">
    <div class="w-50 bg-success text-white rounded-2 me-2">
        <i class='bx bx-list-check p-2 m-3 rounded-2' style="background-color: rgba(255, 255, 255, 0.16); font-size: 18px;"></i>
        <div class="mx-3 my-1">
            Good
            <div>
                {{$countGood}}
            </div>
        </div>
    </div>
    <div class="w-50 rounded-2 me-2" style="background-color: yellow;">
        <i class='bx bx-color-fill p-2 ms-3 m-3 rounded-2' style="background-color: white; font-size: 18px;"></i>
        <div class="mx-3 mt-1 ">
            Medium
            <div>
                {{$countMedium}}
            </div>
        </div>
    </div>
    <div class="w-50 bg-warning text-white rounded-2 me-2">
        <i class='bx bx-error p-2 ms-3 m-3 rounded-2' style="background-color: rgba(255, 204, 145, 1); font-size: 18px;"></i>
        <div class="mx-3 my-1">
            Bad
            <div>
                {{$countBad}}
            </div>
        </div>
    </div>
    <div class="w-50 bg-danger text-white rounded-2">
        <i class='bx bx-no-entry p-2 m-3 rounded-2' style="background-color: rgba(255, 204, 145, 0.16); font-size: 18px;"></i>
        <div class="mx-3 my-1">
            Broken
            <div>
                {{$countBroken}}
            </div>
        </div>
    </div>
</div>

<div class="mt-1 rounded bg-white">
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

    <div class="mt-1 rounded bg-white">
        <table class="table table-striped table-hover">
            <thead class="border-bottom">
                <tr class="table-primary">
                    <th class="col" style="padding-left: 20px;">S.No</th>
                    <th class="col">ID</th>
                    <th class="col">Item</th>
                    <th class="col">Category</th>
                    <th class="col">Price</th>
                    <th class="col">Status</th>
                    <th class="col">Sponsor</th>
                    <th scope="col" style="width: 200px; text-align: center;">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($items as $item)
                <tr>
                    <td style="padding-left: 20px;">{{ $item->id }}</td>
                    <td>{{$item->item_id}}</td>
                    <td>{{ $item->title }}</td>
                    <td>{{ $item->category }}</td>
                    <td>{{ $item->price}}</td>
                    <td>{{ $item->status }}</td>
                    <td>{{ $item->name }}</td>
                    <td style="text-align: center;">
                        <form action="{{ route('items.destroy',$item->id) }}" method="Post">
                            <a class="btn btn-warning text-white" href="#viewItem{{$item->id}}" data-bs-toggle="modal">View</a>
                            <a class="btn btn-primary" href="{{ route('items.edit',$item->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <a href="#deleteClarify{{$item->id}}" data-bs-toggle="modal" class="btn btn-danger">
                                Delete
                            </a>
                            {{-- Comfirm Delete Item  --}}
                            <div class="modal fade" id="deleteClarify{{$item->id}}" tabindex="-1" aria-labelledby="deleteBuildingModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteBuildingModalLabel">Confirm Message</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <form action="{{ route('items.destroy',$item->id) }}" method="Post">

                                            @csrf
                                            @method('DELETE')
                                            <div class="p-3">Are you sure you want to delete this item?</div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </form>
                        {{-- View an item  --}}
                        <div class="modal fade" id="viewItem{{$item->id}}" tabindex="-1" aria-labelledby="ViewEmployeeModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="viewItemModalLabel">Item <b>{{$item->title}}</b> Description</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="d-flex px-3">
                                        <div class="w-100 text-start text-primary">
                                            <p class=""><b>ID: </b></p>
                                            <p><b>Name: </b></p>
                                            <p><b>Price: </b></p>
                                            <p><b>Status: </b></p>
                                            <p><b>Sponsor: </b></p>
                                            <p><b>Description: </b></p>
                                        </div>
                                        <div class="w-100 text-start">
                                            <p>{{$item->id}}</p>
                                            <p>{{$item->title}}</p>
                                            <p>{{$item->price}}</p>
                                            <p>{{$item->status}}</p>
                                            <p>{{$item->name}}</p>
                                            <p>{{$item->description}}</p>
                                        </div>
                                        <div class="w-100 d-flex align-items-center text-start">
                                            <img id="output" width="300" height="200" src="{{ url('public/Image/'.$item->url)}}" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<div class="d-flex justify-content-center">
    {!! $items->links() !!}
</div>
@endsection