routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\ItemController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::redirect('/', '/dashboard');
Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
Route::resource('categories',App\Http\Controllers\CategoryController::class);
Route::resource('items',App\Http\Controllers\ItemController::class);
Route::resource('transactions',App\Http\Controllers\TransactionController::class);
Route::resource('buildings', App\Http\Controllers\BuildingController::class);
Route::resource('rooms', App\Http\Controllers\RoomController::class);
Route::resource('setting',App\Http\Controllers\SettingController::class);
Route::resource('employees',App\Http\Controllers\EmployeeController::class);
Route::resource('status',App\Http\Controllers\StatusController::class);
Route::resource('sponsor',App\Http\Controllers\SponsorController::class);
Route::get('generate-pdf-item', [App\Http\Controllers\ItemController::class,'createPDF'])->name('download');
Route::get('generate-pdf-transaction', [App\Http\Controllers\TransactionController::class,'createPDF'])->name('download-pdf');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $table = 'employees';

    protected $fillable = [
        'firstname',
        'lastname',
        'gender',
        'email',
        'phone_number',
    ];
    public function transactions(){
        return $this->hasOne(Transaction::class);
    }
    public function image(){
        return $this->hasMany(EmployeeImage::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;
use App\Models\EmployeeImage;
use Illuminate\Support\Facades\DB;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        //
        $employees = Employee::where([
            ['lastname', '!=', Null],
            [function ($query) use ($request) {
                if ($term = $request->term) {
                    $query->orWhere('lastname', 'LIKE', '%' . $term . '%')
                        ->orWhere('firstname', 'like', '%' . $term . '%')
                        ->get();
                }
            }]
        ])
        ->join('employeeimages', 'employees.id', '=', 'employeeimages.employee_id')
        ->select('employees.id','employees.firstname','employees.lastname','employees.email','employees.phone_number','employees.gender','employees.created_at','employeeimages.url')
        ->orderBy('id', 'desc')->paginate(10);
        
        $count = DB::table('employees')->count();
        return view('Employee.index')->with(compact('employees'))->with(compact('count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Employee.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // Employee::create($request->post()); 
        $request->validate(['email'=>'unique:employees',
    'phone_number'=>'unique:employees']);
        $employee = new Employee();
        $employee['firstname'] = $request->firstname;
        $employee['lastname'] = $request->lastname;
        $employee['gender'] = $request->gender;
        $employee['email'] = $request->email;
        $employee['phone_number'] = $request->phone_number;

        $employee->save();


        $data = new EmployeeImage();

        if ($request->file('images')) {
            $file = $request->file('images');
            $filename = date('YmdHi') . $file->getClientOriginalName();
            $file->move(public_path('public/Image'), $filename);
            $data['url'] = $filename;
        }
        $data['employee_id'] = $employee->id;
        $data->save();

        return redirect()->route('employees.index')->with('success', 'Employee created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        //
        $image = DB::table('employees')
            ->join('employeeimages', 'employees.id', '=', 'employeeimages.employee_id')
            ->select('employeeimages.url')
            ->where('employeeimages.employee_id', '=', $employee->id)->get();
        return view('Employee.edit')->with(compact('employee'))->with(compact('image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        //
        $request->validate(['email'=>'unique',
        'phone_number'=>'unique']);
        $employee->fill($request->post())->save();

        return redirect()->route('employees.index')->with('success', 'Employee Has Been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        //
        $deleteImage = DB::table('employeeimages')->where('employee_id', '=', $employee->id)->delete();
        $employee->delete();
        return redirect()->route('employees.index')->with('success', 'Employee Has Been removed successfully');
    }
}

resources/views/Employee/create.blade.php
@extends('layouts.app')
@section('title')
Employee
@endsection

@section('content')
<div style="height: 80vh;" class="m-3 mb-5 bg-white rounded-3">
    <form action="{{ route('employees.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="d-flex justify-content-around">
            <div class="row m-5">
                <div class="d-flex justify-content-center">
                    <div class="d-flex justify-content-start">
                        <i style="font-size: 30px;" class='bx bxs-user'></i>
                        <h3 class="ms-3">Create New Employee!</h3>
                    </div>
                </div>
                <div class="my-2">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <label for="firstname">Firstname</label>
                            <input type="text" name="firstname" class="form-control" placeholder="Input employee firstname">
                            {{-- @error('name')
                            <div class="alert alert-danger mt-1 mb-1">{{ $message }}
                        </div>
                        @enderror --}}
                    </div>
                </div>
                <div class="my-2">
                    <div class="form-group">
                        <label for="lastname">Lastname</label>
                        <input type="text" name="lastname" class="form-control" placeholder="Input employee lastname">
                    </div>
                </div>
                <div class="mb-2">
                    <label for="gender">Gender</label>
                    <select  class="form-select" name="gender" id="">
                        <option value="Female">Female</option>
                        <option value="Male">Male</option>
                    </select>
                </div>
                <div class="mb-2">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" class="form-control" placeholder="user@gmail.com">
                    </div>
                </div>
                <div class="mb-2">
                    <div class="form-group">
                        <label for="phone-number">Phone number</label>
                        <input type="number" name="phone_number" class="form-control" placeholder="087 xxxxxx32">
                    </div>
                </div>
                <div class="my-3 d-flex flex-row-reverse">
                    <button type="submit" class="btn btn-primary ms-2"><i class="bx bx-save pe-1"></i>Save</button>
                    <a class="btn btn-secondary" href="{{ route('employees.index') }}"> Back</a>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column me-5">
            <div style="margin-top: 100px;" class="border text-center">
                <img id="output" width="400" height="300" src="{{ asset('images/user.png') }}" />
            </div>
            <div class="d-flex my-3">
                <input type="file" name="images" id="actual-btn" onchange="loadFile(event)" hidden>
                <label style="cursor: pointer;" class="bg-success text-white p-2 rounded text-center" for="actual-btn">Choose File</label>
                <div id="file-chosen" class="py-2 ps-2" style="width: 400px;">No file chosen</div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    var fileChosen = document.getElementById('file-chosen');
    var loadFile = function(event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
        fileChosen.textContent = event.target.files[0].name
    };
</script>
@endsection

resources/views/Employee/edit.blade.php
@extends('layouts.app')
@section('title')
Employee
@endsection

@section('content')
<div style="height: 80vh;" class="m-3 mb-5 bg-white rounded-3">
    <form action="{{ route('employees.update',$employee->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="d-flex justify-content-around">
            <div class="row m-5">
                <div class="d-flex justify-content-center">
                    <div class="d-flex justify-content-start">
                        <i style="font-size: 30px;" class='bx bxs-user'></i>
                        <h3 class="ms-3">Update Employee!</h3>
                    </div>
                </div>
                <div class="my-2">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Firstname:</strong>
                            <input type="text" name="firstname" class="form-control" placeholder="Firstname" value="{{$employee->firstname}}">
                            {{-- @error('name')
                            <div class="alert alert-danger mt-1 mb-1">{{ $message }}
                        </div>
                        @enderror --}}
                    </div>
                </div>
                <div class="my-2">
                    <div class="form-group">
                        <strong>Lastname:</strong>
                        <input type="text" name="lastname" class="form-control" placeholder="Lastname" value="{{$employee->lastname}}">
                    </div>
                </div>
                <div class="mb-2">
                    <div class="form-group">
                        <label for="gender">Gender</label>
                        <select name="gender" class="form-select" id="">
                            @if($employee->gender=="Female")
                            <option value="{{$employee->gender}}">{{$employee->gender}}</option>
                            <option value="Male">Male</option>
                            @elseif($employee->gender=="Male")
                            <option value="{{$employee->gender}}">{{$employee->gender}}</option>
                            <option value="Female">Female</option>
                            @endif
                        </select>
                    </div>
                </div>
                <div class="my-2">
                    <div class="form-group">
                        <strong>Email:</strong>
                        <input type="email" name="email" class="form-control" placeholder="Email" value="{{$employee->email}}">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Phone Number:</strong>
                        <input type="number" name="phone_number" class="form-control" placeholder="Phone number" value="{{$employee->phone_number}}">
                    </div>
                </div>
                <div class="my-3 d-flex flex-row-reverse">
                    <button type="submit" class="btn btn-primary ms-2"><i class="bx bx-save pe-1"></i>Confirm</button>
                    <a class="btn btn-secondary" href="{{ route('employees.index') }}"> Back</a>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column me-5">
            <div style="margin-top: 100px;" class="border text-center">
                @foreach ($image as $image1)
                     <img id="output" width="400" height="300" src="{{ url('public/Image/'.$image1->url) }}" alt="">
                @endforeach
            </div>
            <div class="d-flex my-3">
                <input type="file" name="images" id="actual-btn" onchange="loadFile(event)" hidden>
                <label style="cursor: pointer;" class="bg-success text-white p-2 rounded text-center" for="actual-btn">Choose File</label>
                <div style="width: 400px;" id="file-chosen" class="py-2 ps-2">No file chosen</div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    var fileChosen = document.getElementById('file-chosen');
    var loadFile = function(event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
        fileChosen.textContent = event.target.files[0].name
    };
</script>
@endsection

resources/views/Employee/index.blade.php
@extends('layouts.app')
@section('title', 'Employee')
@section('content')
<div class="container text-center">
    <h2 class="modal-title p-2" id="buildingModalLabel">Employee Inventory</h2>
</div>
    <div style="position: sticky;padding: 10px 0px 0 0px; top: 60px; overflow: hidden;background: #e4e9f7;"
        class="d-flex justify-content-between mb-3">
        <div class="w-25 d-flex justify-content-start text-white bg-primary rounded-2 me-2">
            <div class="text-white"> <i class='bx bxs-group p-2 m-3 rounded-2'
                    style="background-color: rgba(255, 255, 255, 0.16); font-size: 18px;"></i></div>
            <div class="m-3">
                All Employees
                <div>
                    {{ $count }}
                </div>
            </div>
        </div>
        <div class=" w-75 d-flex align-items-center text-white bg-white rounded-2 me-2">
            <div class="d-flex w-100 justify-content-between px-3">
                {{-- search bar --}}
                <form class="w-50" action="{{ route('employees.index') }}" method="GET" role="search">
                    <div class="d-flex justify-content-start">
                        <div class="input-group">
                            <input type="text" class="form-control mr-2 w-100 ps-3" name="term"
                                placeholder="Search Employee" id="term">
                        </div>
                        <span class="input-group-btn ms-2">
                            <button class="btn btn-primary d-flex align-items-center h-100" type="submit"
                                title="Search Employee">
                                <i style=" font-size: 18px;" class='bx bx-search'></i>
                            </button>
                        </span>
                    </div>
                </form>
                <a class="text-white text-decoration-none" href="{{ route('employees.create') }}">
                    <div class="btn btn-primary d-flex justify-conten-between">
                        <div class="me-2 d-flex align-items-center">
                            <i style="font-size: 18px;" class='bx bx-plus text-white'></i>
                        </div>
                        <span>Add New</span>
                    </div>
                </a>
            </div>
        </div>
    </div>

    <div class="mt-1 rounded bg-white">
        <div class="row">
        </div>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        <table class="table table-striped table-hover">
            <thead>
                <tr class="table-primary">
                    <th scope="col" style="padding-left: 20px;">S.No</th>
                    <th scope="col">Name</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone Number</th>
                    <th scope="col" style="width: 200px; text-align: center;">Action</th>  
                </tr>
            </thead>
            <tbody>
                @foreach ($employees as $employee)
                    <tr>
                        <td scope="row" style="padding-left: 20px;">{{ $employee->id }}</td>
                        <td>{{ $employee->firstname }} {{ $employee->lastname }}</td>
                        <td>{{ $employee->gender }}</td>
                        <td>{{ $employee->email }}</td>
                        <td>{{ $employee->phone_number }}</td> 
                        <td style="text-align: center;">
                            <form action="{{ route('employees.destroy', $employee->id) }}" method="Post">
                                <a class="btn btn-warning text-white" href="#viewEmployee{{ $employee->id }}" data-bs-toggle="modal">View</a>
                                <a class="btn btn-primary" href="{{ route('employees.edit', $employee->id) }}">Edit</a>
                                @csrf
                                @method('DELETE')
                                <a href="#deleteClarify{{ $employee->id }}" data-bs-toggle="modal" class="btn btn-danger">
                                    Delete
                                </a>
                                {{-- Comfirm Delete Room  --}}
                                <div class="modal fade" id="deleteClarify{{ $employee->id }}" tabindex="-1"
                                    aria-labelledby="deleteBuildingModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="deleteBuildingModalLabel">Confirm Message
                                                </h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <form action="{{ route('employees.destroy', $employee->id) }}" method="Post">

                                                @csrf
                                                @method('DELETE')
                                                <div class="p-3">Are you sure you want to delete this employee?</div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-bs-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            {{-- View an employee  --}}
                            <div class="modal fade" id="viewEmployee{{ $employee->id }}" tabindex="-1" aria-labelledby="ViewEmployeeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="viewItemModalLabel">Employee</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="d-flex px-3">
                                            <div class="w-100 text-start text-primary">
                                                <p><b>ID: </b></p>
                                                <p><b>Name: </b></p>
                                                <p><b>Gender: </b></p>
                                                <p><b>Email: </b></p>
                                                <p><b>Phone Number: </b></p>
                                                <p><b>Created At: </b></p>
                                            </div>
                                            <div class="w-100 text-start">
                                                <p>{{$employee->id}}</p>
                                                <p>{{$employee->firstname}} {{$employee->lastname}}</p>
                                                <p>{{$employee->gender}}</p>
                                                <p>{{$employee->email}}</p>
                                                <p>{{$employee->phone_number}}</p>
                                                <p>{{$employee->created_at}}</p>
                                            </div> 
                                            <div class="w-100 d-flex align-items-center text-start">
                                                 <img id="output" width="300" height="200" src="{{ url('public/Image/'.$employee->url) }}" />
                                            </div> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
<div class="d-flex justify-content-center">
    {!! $employees->links() !!}
</div>
@endsection